### ISSUE TITLE
Error using dplyr::selection

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/scidb.dplyr#10]
I think I may have broken the distribution, but I'm unsure how at the moment.
 See below:
```
library(scidb.dplyr)

#connect to scidb
db = scidbconnect()

#insert iris dataset into scidb using the SciDB-R package
x  = as.scidb(db, iris)    # a 'scidb' object

#create a scidb dplyr object from the scidb array object
d  = tbl(x)                # a 'tbl_scidb' object (dplyr)

#Non-standard evaluation 
#selection and filter examples
dplyr::select(d, Petal_Length, Species)

SciDB expression  project(R_array2a246f7502e314957481...
Error: HTTP error 500
UserQueryException in file: src/query/parser/Translator.cpp function: matchOperatorParam line: 1408
Error id: scidb::SCIDB_SE_QPROC::SCIDB_LE_WRONG_OPERATOR_ARGUMENT2
Error description: Query processor error. Parameter must be attribute name.
filter(project(R_array2a246f7502e31495748174872539702, NA,NA), true)
                                                      ^^^
```

**Comment by jrivers96** [comment]
I must have something wrong with a package in my environment. I am getting the below now. Continuing to look at this...

```
 dplyr::select(d, Petal_Length, Species)
 Hide Traceback
 
 Rerun with Debug
 Error in value[[3L]](cond) : could not find function "call2str" 
9 value[[3L]](cond) 
8 tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
7 tryCatchList(expr, classes, parentenv, handlers) 
6 tryCatch({
    if (class(eval(.x$expr, envir = .x$env))[1] %in% "scidb") {
        eval(.x$expr, envir = .x$env)@name
    } ... at tbl_scidb.R#168
5 FUN(X[[i]], ...) 
4 lapply(dots, function(.x) tryCatch({
    if (class(eval(.x$expr, envir = .x$env))[1] %in% "scidb") {
        eval(.x$expr, envir = .x$env)@name
    } ... at tbl_scidb.R#167
3 select_.tbl_scidb(.data, .dots = lazyeval::lazy_dots(...)) 
2 select_(.data, .dots = lazyeval::lazy_dots(...)) 
1 dplyr::select(d, Petal_Length, Species) 
```

**Comment by jrivers96** [comment]
I rolled back to the commit d30c6f5adad20b2567f809c44e300d07f0c30e1e which is before my changes and I still have the problems. 

Where does the function call2str come from? I can't seem to find it anywhere?

**Comment by bwlewis** [comment]
Yes, this is indeed a bug. I introduced it when I added support for the dplyr starts_with, etc. matching functions.

Fixing this...

We need to add tests to the package to catch these regressions.

**Comment by bwlewis** [comment]
should be fixed now

**Comment by jrivers96** [comment]
I still get the error below. Where do I find the function call2str?
``` 
Error in value[[3L]](cond) : could not find function "call2str" 
```

**Comment by bwlewis** [comment]
it's an internal function in the scidb.dplyr package

**Comment by jrivers96** [comment]
It works. I had some RStudio caching problems going on.
